build: false  # Tell appveyor to not use msbuild

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37
      PYTHON_ARCH: "32"
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37-x64
      PYTHON_ARCH: "64"
  PYPI_PASSWORD:
    secure: Zw0hha0+/4KCvYqgBYpOHGbrc9jrvtHq8N0xXkWSvLk=

# platform:
#   - x64
#   - x86

init:
#  - ps: Start-FileDownload 'http://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi' C:\VCForPython27.msi; echo "Done"
#  - cmd: msiexec /i C:\VCForPython27.msi /quiet /qn

install:
  # Miniconda setup + necessary external packages
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - conda update --yes conda
  - conda info -a
  - conda install --yes cython numpy pytables nose twine
  - pip install -e .
  - conda list

test_script:
  - nosetests

after_test:
  - python setup.py bdist_wheel
  - ps: rm dist/*.egg

artifacts:
  - path: dist\*
    name: pypiartifacts

deploy_script:
  - echo "Starting deployment"
  - echo [distutils] > %USERPROFILE%\\.pypirc
  - echo index-servers = >> %USERPROFILE%\\.pypirc
  - echo     pypi >> %USERPROFILE%\\.pypirc
  - echo [pypi] >> %USERPROFILE%\\.pypirc
  - echo username=laborleben >> %USERPROFILE%\\.pypirc
  - echo password=%PYPI_PASSWORD% >> %USERPROFILE%\\.pypirc
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_BRANCH -eq "master") { Invoke-Expression "twine upload --skip-existing dist/*.whl" 2>$null } Else { write-output "Not on a tag on master, won't deploy"}
  - echo "Finished deployment"
